repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: "db98579"
    hooks:
      - id: pycln
  - repo: https://github.com/timothycrosley/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: debug-statements
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: .gitignore
      - id: name-tests-test
      - id: no-commit-to-branch
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
  - repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: v0.3.3
    hooks:
      - id: pep257
